#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Demos.Droid.Resource", IsApplication=true)]

namespace Demos.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::HockeyApp.Resource.Color.hockeyapp_background_header = global::Demos.Droid.Resource.Color.hockeyapp_background_header;
			global::HockeyApp.Resource.Color.hockeyapp_background_light = global::Demos.Droid.Resource.Color.hockeyapp_background_light;
			global::HockeyApp.Resource.Color.hockeyapp_background_white = global::Demos.Droid.Resource.Color.hockeyapp_background_white;
			global::HockeyApp.Resource.Color.hockeyapp_button_background = global::Demos.Droid.Resource.Color.hockeyapp_button_background;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_pressed = global::Demos.Droid.Resource.Color.hockeyapp_button_background_pressed;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_selected = global::Demos.Droid.Resource.Color.hockeyapp_button_background_selected;
			global::HockeyApp.Resource.Color.hockeyapp_text_black = global::Demos.Droid.Resource.Color.hockeyapp_text_black;
			global::HockeyApp.Resource.Color.hockeyapp_text_light = global::Demos.Droid.Resource.Color.hockeyapp_text_light;
			global::HockeyApp.Resource.Color.hockeyapp_text_normal = global::Demos.Droid.Resource.Color.hockeyapp_text_normal;
			global::HockeyApp.Resource.Color.hockeyapp_text_white = global::Demos.Droid.Resource.Color.hockeyapp_text_white;
			global::HockeyApp.Resource.Drawable.hockeyapp_btn_background = global::Demos.Droid.Resource.Drawable.hockeyapp_btn_background;
			global::HockeyApp.Resource.Id.button_add_response = global::Demos.Droid.Resource.Id.button_add_response;
			global::HockeyApp.Resource.Id.button_attachment = global::Demos.Droid.Resource.Id.button_attachment;
			global::HockeyApp.Resource.Id.button_login = global::Demos.Droid.Resource.Id.button_login;
			global::HockeyApp.Resource.Id.button_refresh = global::Demos.Droid.Resource.Id.button_refresh;
			global::HockeyApp.Resource.Id.button_send = global::Demos.Droid.Resource.Id.button_send;
			global::HockeyApp.Resource.Id.button_update = global::Demos.Droid.Resource.Id.button_update;
			global::HockeyApp.Resource.Id.input_email = global::Demos.Droid.Resource.Id.input_email;
			global::HockeyApp.Resource.Id.input_message = global::Demos.Droid.Resource.Id.input_message;
			global::HockeyApp.Resource.Id.input_name = global::Demos.Droid.Resource.Id.input_name;
			global::HockeyApp.Resource.Id.input_password = global::Demos.Droid.Resource.Id.input_password;
			global::HockeyApp.Resource.Id.input_subject = global::Demos.Droid.Resource.Id.input_subject;
			global::HockeyApp.Resource.Id.label_author = global::Demos.Droid.Resource.Id.label_author;
			global::HockeyApp.Resource.Id.label_date = global::Demos.Droid.Resource.Id.label_date;
			global::HockeyApp.Resource.Id.label_last_updated = global::Demos.Droid.Resource.Id.label_last_updated;
			global::HockeyApp.Resource.Id.label_message = global::Demos.Droid.Resource.Id.label_message;
			global::HockeyApp.Resource.Id.label_text = global::Demos.Droid.Resource.Id.label_text;
			global::HockeyApp.Resource.Id.label_title = global::Demos.Droid.Resource.Id.label_title;
			global::HockeyApp.Resource.Id.label_version = global::Demos.Droid.Resource.Id.label_version;
			global::HockeyApp.Resource.Id.list_attachments = global::Demos.Droid.Resource.Id.list_attachments;
			global::HockeyApp.Resource.Id.list_feedback_messages = global::Demos.Droid.Resource.Id.list_feedback_messages;
			global::HockeyApp.Resource.Id.text_headline = global::Demos.Droid.Resource.Id.text_headline;
			global::HockeyApp.Resource.Id.view_header = global::Demos.Droid.Resource.Id.view_header;
			global::HockeyApp.Resource.Id.web_update_details = global::Demos.Droid.Resource.Id.web_update_details;
			global::HockeyApp.Resource.Id.wrapper_attachments = global::Demos.Droid.Resource.Id.wrapper_attachments;
			global::HockeyApp.Resource.Id.wrapper_feedback = global::Demos.Droid.Resource.Id.wrapper_feedback;
			global::HockeyApp.Resource.Id.wrapper_feedback_scroll = global::Demos.Droid.Resource.Id.wrapper_feedback_scroll;
			global::HockeyApp.Resource.Id.wrapper_messages = global::Demos.Droid.Resource.Id.wrapper_messages;
			global::HockeyApp.Resource.Id.wrapper_messages_buttons = global::Demos.Droid.Resource.Id.wrapper_messages_buttons;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_expiry_info = global::Demos.Droid.Resource.Layout.hockeyapp_activity_expiry_info;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_feedback = global::Demos.Droid.Resource.Layout.hockeyapp_activity_feedback;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_login = global::Demos.Droid.Resource.Layout.hockeyapp_activity_login;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_update = global::Demos.Droid.Resource.Layout.hockeyapp_activity_update;
			global::HockeyApp.Resource.Layout.hockeyapp_fragment_update = global::Demos.Droid.Resource.Layout.hockeyapp_fragment_update;
			global::HockeyApp.Resource.Layout.hockeyapp_view_feedback_message = global::Demos.Droid.Resource.Layout.hockeyapp_view_feedback_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_app_name_fallback = global::Demos.Droid.Resource.String.hockeyapp_crash_dialog_app_name_fallback;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_message = global::Demos.Droid.Resource.String.hockeyapp_crash_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_negative_button = global::Demos.Droid.Resource.String.hockeyapp_crash_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_neutral_button = global::Demos.Droid.Resource.String.hockeyapp_crash_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_positive_button = global::Demos.Droid.Resource.String.hockeyapp_crash_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_title = global::Demos.Droid.Resource.String.hockeyapp_crash_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_message = global::Demos.Droid.Resource.String.hockeyapp_dialog_error_message;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_title = global::Demos.Droid.Resource.String.hockeyapp_dialog_error_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_negative_button = global::Demos.Droid.Resource.String.hockeyapp_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_dialog_positive_button = global::Demos.Droid.Resource.String.hockeyapp_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_message = global::Demos.Droid.Resource.String.hockeyapp_download_failed_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_negative_button = global::Demos.Droid.Resource.String.hockeyapp_download_failed_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_positive_button = global::Demos.Droid.Resource.String.hockeyapp_download_failed_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_title = global::Demos.Droid.Resource.String.hockeyapp_download_failed_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_error_no_network_message = global::Demos.Droid.Resource.String.hockeyapp_error_no_network_message;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_text = global::Demos.Droid.Resource.String.hockeyapp_expiry_info_text;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_title = global::Demos.Droid.Resource.String.hockeyapp_expiry_info_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_file = global::Demos.Droid.Resource.String.hockeyapp_feedback_attach_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_picture = global::Demos.Droid.Resource.String.hockeyapp_feedback_attach_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_button_text = global::Demos.Droid.Resource.String.hockeyapp_feedback_attachment_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_error = global::Demos.Droid.Resource.String.hockeyapp_feedback_attachment_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_loading = global::Demos.Droid.Resource.String.hockeyapp_feedback_attachment_loading;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint = global::Demos.Droid.Resource.String.hockeyapp_feedback_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_text = global::Demos.Droid.Resource.String.hockeyapp_feedback_failed_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_title = global::Demos.Droid.Resource.String.hockeyapp_feedback_failed_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_fetching_feedback_text = global::Demos.Droid.Resource.String.hockeyapp_feedback_fetching_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_generic_error = global::Demos.Droid.Resource.String.hockeyapp_feedback_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_last_updated_text = global::Demos.Droid.Resource.String.hockeyapp_feedback_last_updated_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_max_attachments_allowed = global::Demos.Droid.Resource.String.hockeyapp_feedback_max_attachments_allowed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint = global::Demos.Droid.Resource.String.hockeyapp_feedback_message_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint = global::Demos.Droid.Resource.String.hockeyapp_feedback_name_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_refresh_button_text = global::Demos.Droid.Resource.String.hockeyapp_feedback_refresh_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_response_button_text = global::Demos.Droid.Resource.String.hockeyapp_feedback_response_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_file = global::Demos.Droid.Resource.String.hockeyapp_feedback_select_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_picture = global::Demos.Droid.Resource.String.hockeyapp_feedback_select_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_button_text = global::Demos.Droid.Resource.String.hockeyapp_feedback_send_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_generic_error = global::Demos.Droid.Resource.String.hockeyapp_feedback_send_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_network_error = global::Demos.Droid.Resource.String.hockeyapp_feedback_send_network_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sending_feedback_text = global::Demos.Droid.Resource.String.hockeyapp_feedback_sending_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint = global::Demos.Droid.Resource.String.hockeyapp_feedback_subject_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_title = global::Demos.Droid.Resource.String.hockeyapp_feedback_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_empty = global::Demos.Droid.Resource.String.hockeyapp_feedback_validate_email_empty;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_error = global::Demos.Droid.Resource.String.hockeyapp_feedback_validate_email_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_name_error = global::Demos.Droid.Resource.String.hockeyapp_feedback_validate_name_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_subject_error = global::Demos.Droid.Resource.String.hockeyapp_feedback_validate_subject_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_text_error = global::Demos.Droid.Resource.String.hockeyapp_feedback_validate_text_error;
			global::HockeyApp.Resource.String.hockeyapp_login_email_hint = global::Demos.Droid.Resource.String.hockeyapp_login_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text = global::Demos.Droid.Resource.String.hockeyapp_login_headline_text;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text_email_only = global::Demos.Droid.Resource.String.hockeyapp_login_headline_text_email_only;
			global::HockeyApp.Resource.String.hockeyapp_login_login_button_text = global::Demos.Droid.Resource.String.hockeyapp_login_login_button_text;
			global::HockeyApp.Resource.String.hockeyapp_login_missing_credentials_toast = global::Demos.Droid.Resource.String.hockeyapp_login_missing_credentials_toast;
			global::HockeyApp.Resource.String.hockeyapp_login_password_hint = global::Demos.Droid.Resource.String.hockeyapp_login_password_hint;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_message = global::Demos.Droid.Resource.String.hockeyapp_paint_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_negative_button = global::Demos.Droid.Resource.String.hockeyapp_paint_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_neutral_button = global::Demos.Droid.Resource.String.hockeyapp_paint_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_positive_button = global::Demos.Droid.Resource.String.hockeyapp_paint_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_indicator_toast = global::Demos.Droid.Resource.String.hockeyapp_paint_indicator_toast;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_clear = global::Demos.Droid.Resource.String.hockeyapp_paint_menu_clear;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_save = global::Demos.Droid.Resource.String.hockeyapp_paint_menu_save;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_undo = global::Demos.Droid.Resource.String.hockeyapp_paint_menu_undo;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_negative_button = global::Demos.Droid.Resource.String.hockeyapp_permission_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_positive_button = global::Demos.Droid.Resource.String.hockeyapp_permission_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_message = global::Demos.Droid.Resource.String.hockeyapp_permission_update_message;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_title = global::Demos.Droid.Resource.String.hockeyapp_permission_update_title;
			global::HockeyApp.Resource.String.hockeyapp_update_button = global::Demos.Droid.Resource.String.hockeyapp_update_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_message = global::Demos.Droid.Resource.String.hockeyapp_update_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_negative_button = global::Demos.Droid.Resource.String.hockeyapp_update_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_positive_button = global::Demos.Droid.Resource.String.hockeyapp_update_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_title = global::Demos.Droid.Resource.String.hockeyapp_update_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_update_mandatory_toast = global::Demos.Droid.Resource.String.hockeyapp_update_mandatory_toast;
			global::HockeyApp.Resource.String.hockeyapp_update_version_details_label = global::Demos.Droid.Resource.String.hockeyapp_update_version_details_label;
			global::HockeyApp.Resource.String.library_name = global::Demos.Droid.Resource.String.library_name;
			global::HockeyApp.Resource.Style.HockeyApp_ButtonStyle = global::Demos.Droid.Resource.Style.HockeyApp_ButtonStyle;
			global::HockeyApp.Resource.Style.HockeyApp_EditTextStyle = global::Demos.Droid.Resource.Style.HockeyApp_EditTextStyle;
			global::HockeyApp.Resource.Style.HockeyApp_SingleLineInputStyle = global::Demos.Droid.Resource.Style.HockeyApp_SingleLineInputStyle;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Demos.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Demos.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroidCipher.Resource.String.ApplicationName = global::Demos.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroidCipher.Resource.String.Hello = global::Demos.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroidCipher.Resource.String.library_name = global::Demos.Droid.Resource.String.library_name;
			global::Xamarin.Platforms.Android.Resource.Attribute.layoutManager = global::Demos.Droid.Resource.Attribute.layoutManager;
			global::Xamarin.Platforms.Android.Resource.Attribute.reverseLayout = global::Demos.Droid.Resource.Attribute.reverseLayout;
			global::Xamarin.Platforms.Android.Resource.Attribute.spanCount = global::Demos.Droid.Resource.Attribute.spanCount;
			global::Xamarin.Platforms.Android.Resource.Attribute.stackFromEnd = global::Demos.Droid.Resource.Attribute.stackFromEnd;
			global::Xamarin.Platforms.Android.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::Demos.Droid.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::Xamarin.Platforms.Android.Resource.Id.item_touch_helper_previous_elevation = global::Demos.Droid.Resource.Id.item_touch_helper_previous_elevation;
			global::Xamarin.Platforms.Android.Resource.String.ApplicationName = global::Demos.Droid.Resource.String.ApplicationName;
			global::Xamarin.Platforms.Android.Resource.String.Hello = global::Demos.Droid.Resource.String.Hello;
			global::Xamarin.Platforms.Android.Resource.String.library_name = global::Demos.Droid.Resource.String.library_name;
			global::Xamarin.Platforms.Android.Resource.Styleable.RecyclerView = global::Demos.Droid.Resource.Styleable.RecyclerView;
			global::Xamarin.Platforms.Android.Resource.Styleable.RecyclerView_android_orientation = global::Demos.Droid.Resource.Styleable.RecyclerView_android_orientation;
			global::Xamarin.Platforms.Android.Resource.Styleable.RecyclerView_layoutManager = global::Demos.Droid.Resource.Styleable.RecyclerView_layoutManager;
			global::Xamarin.Platforms.Android.Resource.Styleable.RecyclerView_reverseLayout = global::Demos.Droid.Resource.Styleable.RecyclerView_reverseLayout;
			global::Xamarin.Platforms.Android.Resource.Styleable.RecyclerView_spanCount = global::Demos.Droid.Resource.Styleable.RecyclerView_spanCount;
			global::Xamarin.Platforms.Android.Resource.Styleable.RecyclerView_stackFromEnd = global::Demos.Droid.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int hockeyapp_background_header = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int hockeyapp_background_light = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int hockeyapp_background_white = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int hockeyapp_button_background = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int hockeyapp_button_background_pressed = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int hockeyapp_button_background_selected = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int hockeyapp_text_black = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int hockeyapp_text_light = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int hockeyapp_text_normal = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int hockeyapp_text_white = 2131230729;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int hockeyapp_btn_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Splash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int button_add_response = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int button_attachment = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int button_login = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int button_refresh = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int button_send = 2131034122;
			
			// aapt resource value: 0x7f050017
			public const int button_update = 2131034135;
			
			// aapt resource value: 0x7f050005
			public const int input_email = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int input_message = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int input_name = 2131034116;
			
			// aapt resource value: 0x7f050012
			public const int input_password = 2131034130;
			
			// aapt resource value: 0x7f050006
			public const int input_subject = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050019
			public const int label_author = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int label_date = 2131034138;
			
			// aapt resource value: 0x7f05000c
			public const int label_last_updated = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int label_message = 2131034113;
			
			// aapt resource value: 0x7f05001b
			public const int label_text = 2131034139;
			
			// aapt resource value: 0x7f050015
			public const int label_title = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int label_version = 2131034134;
			
			// aapt resource value: 0x7f05001c
			public const int list_attachments = 2131034140;
			
			// aapt resource value: 0x7f050010
			public const int list_feedback_messages = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int text_headline = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int view_header = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int web_update_details = 2131034136;
			
			// aapt resource value: 0x7f050008
			public const int wrapper_attachments = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int wrapper_feedback = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int wrapper_feedback_scroll = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int wrapper_messages = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int wrapper_messages_buttons = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int hockeyapp_activity_expiry_info = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int hockeyapp_activity_feedback = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int hockeyapp_activity_login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int hockeyapp_activity_update = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int hockeyapp_fragment_update = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int hockeyapp_view_feedback_message = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int ApplicationName = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int Hello = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int hockeyapp_crash_dialog_app_name_fallback = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int hockeyapp_crash_dialog_message = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int hockeyapp_crash_dialog_negative_button = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int hockeyapp_crash_dialog_neutral_button = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int hockeyapp_crash_dialog_positive_button = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int hockeyapp_crash_dialog_title = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int hockeyapp_dialog_error_message = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int hockeyapp_dialog_error_title = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int hockeyapp_dialog_negative_button = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int hockeyapp_dialog_positive_button = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int hockeyapp_download_failed_dialog_message = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int hockeyapp_download_failed_dialog_negative_button = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int hockeyapp_download_failed_dialog_positive_button = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int hockeyapp_download_failed_dialog_title = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int hockeyapp_error_no_network_message = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int hockeyapp_expiry_info_text = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int hockeyapp_expiry_info_title = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int hockeyapp_feedback_attach_file = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int hockeyapp_feedback_attach_picture = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int hockeyapp_feedback_attachment_button_text = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int hockeyapp_feedback_attachment_error = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int hockeyapp_feedback_attachment_loading = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int hockeyapp_feedback_email_hint = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int hockeyapp_feedback_failed_text = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int hockeyapp_feedback_failed_title = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int hockeyapp_feedback_fetching_feedback_text = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int hockeyapp_feedback_generic_error = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int hockeyapp_feedback_last_updated_text = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int hockeyapp_feedback_max_attachments_allowed = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int hockeyapp_feedback_message_hint = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int hockeyapp_feedback_name_hint = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int hockeyapp_feedback_refresh_button_text = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int hockeyapp_feedback_response_button_text = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int hockeyapp_feedback_select_file = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int hockeyapp_feedback_select_picture = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int hockeyapp_feedback_send_button_text = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int hockeyapp_feedback_send_generic_error = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int hockeyapp_feedback_send_network_error = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int hockeyapp_feedback_sending_feedback_text = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int hockeyapp_feedback_subject_hint = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int hockeyapp_feedback_title = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int hockeyapp_feedback_validate_email_empty = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int hockeyapp_feedback_validate_email_error = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int hockeyapp_feedback_validate_name_error = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int hockeyapp_feedback_validate_subject_error = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int hockeyapp_feedback_validate_text_error = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int hockeyapp_login_email_hint = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int hockeyapp_login_headline_text = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int hockeyapp_login_headline_text_email_only = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int hockeyapp_login_login_button_text = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int hockeyapp_login_missing_credentials_toast = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int hockeyapp_login_password_hint = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int hockeyapp_paint_dialog_message = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int hockeyapp_paint_dialog_negative_button = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int hockeyapp_paint_dialog_neutral_button = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int hockeyapp_paint_dialog_positive_button = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int hockeyapp_paint_indicator_toast = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int hockeyapp_paint_menu_clear = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int hockeyapp_paint_menu_save = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int hockeyapp_paint_menu_undo = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int hockeyapp_permission_dialog_negative_button = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int hockeyapp_permission_dialog_positive_button = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int hockeyapp_permission_update_message = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int hockeyapp_permission_update_title = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int hockeyapp_update_button = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int hockeyapp_update_dialog_message = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int hockeyapp_update_dialog_negative_button = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int hockeyapp_update_dialog_positive_button = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int hockeyapp_update_dialog_title = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int hockeyapp_update_mandatory_toast = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int hockeyapp_update_version_details_label = 2131099721;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int HockeyApp_ButtonStyle = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int HockeyApp_EditTextStyle = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int HockeyApp_SingleLineInputStyle = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int Theme_Splash = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
